---
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: lab-storage
  namespace: democratic-csi
spec:
  config: |-
    {
      "cniVersion": "0.3.1",
      "name": "lab-storage",
      "type": "macvlan",
      "master": "br-storage",
      "mode": "bridge",
      "mtu": 1500,
      "ipam": {
        "type": "whereabouts",
        "range": "192.168.11.0/24",
        "exclude": [
          "192.168.11.0/26"
        ]
      }
    }
