kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: seaweedfs-worker-logs
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: lvms-vg1
  volumeMode: Filesystem
