---
apiVersion: aap.ansible.com/v1alpha1
kind: AnsibleAutomationPlatform
metadata:
  name: aap
  namespace: ansible-automation-platform
spec:
  image_pull_policy: IfNotPresent
  route_tls_termination_mechanism: Edge
  no_log: true
  redis_mode: standalone
  api:
    log_level: INFO
    replicas: 1
  database:
    postgres_data_volume_init: false
    idle_disabled: false
    postgres_storage_class: fast-nfs
  service_type: ClusterIP
  ingress_type: Route
  route_host: aap.apps.core.lab.cross.solutions
  controller:
    disabled: false
  eda:
    disabled: false
  hub:
    disabled: false
    storage_type: file
    file_storage_size: 20Gi
    file_storage_storage_class: fast-nfs
  lightspeed:
    disabled: true
