---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-cluster-api-cert
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
  - apiGroups:
      - config.openshift.io
    resources:
      - apiservers
    verbs:
      - get
      - list
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-cluster-api-cert
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patch-cluster-api-cert
subjects:
  - kind: ServiceAccount
    name: patch-cluster-api-cert
    namespace: openshift-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch-cluster-api-cert
  namespace: openshift-config
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-cluster-api-cert
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - image: quay.io/openshift/origin-cli:latest
          env:
            - name: API_HOST_NAME
              value: api.core.lab.cross.solutions
            - name: NAMESPACE
              value: openshift-config
            - name: SECRET
              value: cluster-api-certificate
          command:
            - /bin/bash
            - -c
            - |
              #!/bin/bash

              until oc -n "$NAMESPACE" get secret "$SECRET" >/dev/null 2>&1; do
                echo "Waiting for $NAMESPACE/$SECRET to exist..."
                sleep 5
              done

              until oc -n "$NAMESPACE" get secret "$SECRET" -o jsonpath='{.data.tls\.crt}' | grep -q . && \
                    oc -n "$NAMESPACE" get secret "$SECRET" -o jsonpath='{.data.tls\.key}' | grep -q .; do
                echo "Waiting for tls.crt/tls.key to be present in $NAMESPACE/$SECRET..."
                sleep 5
              done

              oc patch apiserver cluster --type=merge -p '{"spec":{"servingCerts":{"namedCertificates":[{"names":["'"$API_HOST_NAME"'"],"servingCertificate":{"name":"'"$SECRET"'"}}]}}}'

          name: patch-cluster-api-cert
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      serviceAccount: patch-cluster-api-cert
      serviceAccountName: patch-cluster-api-cert
