apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: cloudnative-pg-operator
  namespace: cloudnative-pg
spec:
  channel: patch-me-channel
  name: cloudnative-pg
  source: operatorhubio-catalog
  sourceNamespace: olm
