---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-reflector-sa-nonroot-v2
  namespace: reflector
subjects:
- kind: ServiceAccount
  name: reflector
  namespace: reflector
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-nonroot-v2-scc
