---
kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - 01-namespace.yaml
  - 02-operatorgroup.yaml
  - 03-subscription.yaml
  - 04-hyperconverged.yaml
  - 05-storageprofile.yaml
