---
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: truenas-nfs-nonroot
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  claimPropertySets:
    - accessModes:
        - ReadWriteMany
        - ReadWriteOnce
      volumeMode:
        Filesystem
