apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak-postgres-config
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: keycloak-postgres
data:
  POSTGRESQL_DATABASE: keycloak
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: keycloak-postgres-pvc
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: keycloak-postgres
spec:
  storageClassName: fast-nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: keycloak-postgres
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: keycloak-postgres
spec:
  serviceName: keycloak-postgres
  replicas: 1
  selector:
    matchLabels:
      app: keycloak-postgres
  template:
    metadata:
      labels:
        app: keycloak-postgres
    spec:
      containers:
        - name: keycloak-postgres
          image: registry.redhat.io/rhel9/postgresql-16
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: keycloak-postgres-config
          env:
            - name: POSTGRESQL_USER
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-creds
                  key: user
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: keycloak-db-creds
                  key: password
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: keycloak-postgres-vm
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "0.5"
      volumes:
        - name: keycloak-postgres-vm
          persistentVolumeClaim:
            claimName: keycloak-postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak-postgres
  namespace: keycloak
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app: keycloak-postgres
spec:
  selector:
    app: keycloak-postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
