apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-tls
  namespace: keycloak
spec:
  data:
    - remoteRef:
        key: core-ingress-wildcard-fullchain
      secretKey: tls.crt
    - remoteRef:
        key: core-ingress-wildcard-key
      secretKey: tls.key
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infra-gcpsm-store
  target:
    name: keycloak-tls
    creationPolicy: Owner
