apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: fast-iscsi-driver-config
  namespace: democratic-csi
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: infra-onepassword-store
  data:
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: patch-me-host
        metadataPolicy: None
      secretKey: host
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: patch-me-https-port
        metadataPolicy: None
      secretKey: https-port
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: patch-me-https-username
        metadataPolicy: None
      secretKey: https-username
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: patch-me-https-api-key
        metadataPolicy: None
      secretKey: https-api-key
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: patch-me-ssh-port
        metadataPolicy: None
      secretKey: ssh-port
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: patch-me-ssh-username
        metadataPolicy: None
      secretKey: ssh-username
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: patch-me-ssh-private-key
        metadataPolicy: None
      secretKey: ssh-private-key
    - remoteRef:
        conversionStrategy: Default
        decodingStrategy: None
        key: patch-me-iscsi-port
        metadataPolicy: None
      secretKey: iscsi-port
  target:
    name: fast-iscsi-driver-config
    creationPolicy: Owner
