apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-per-cluster
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - git:
        repoURL: https://github.com/wtcross/homelab.git
        revision: main
        files:
          - path: "openshift-gitops/clusters/**/cluster-config.yaml"

  template:
    metadata:
      name: '{{.cluster.name}}-external-secrets'
      annotations:
        argocd.argoproj.io/sync-wave: "4"
    spec:
      destination:
        namespace: external-secrets
        server: https://kubernetes.default.svc
      project: infra
      source:
        chart: external-secrets
        repoURL: https://charts.external-secrets.io
        targetRevision: 1.1.0
        helm:
          releaseName: external-secrets
          valuesObject:
            installCRDs: true
            openshiftFinalizers: true
            metrics:
              enabled: true
              service:
                port: 8080
            grafanaDashboard:
              enabled: true
            resources:
              requests:
                cpu: 10m
                memory: 96Mi
              limits:
                cpu: 100m
                memory: 256Mi
      syncPolicy:
        automated:
          allowEmpty: false
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
