apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-per-cluster
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]

  generators:
    - git:
        repoURL: https://github.com/wtcross/homelab.git
        revision: main
        files:
          - path: "openshift-gitops/clusters/**/cluster-config.yaml"

  template:
    metadata:
      name: '{{.cluster.name}}-infra'
      annotations:
        argocd.argoproj.io/sync-wave: "5"
    spec:
      project: infra
      source:
        repoURL: https://github.com/wtcross/homelab.git
        targetRevision: main
        path: "{{.path.path}}/05-infra"
      destination:
        server: https://kubernetes.default.svc
        namespace: openshift-gitops
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - SkipDryRunOnMissingResource=true
