apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infra-gcpsm-store
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "0"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  provider:
    gcpsm:
      auth:
        secretRef:
          secretAccessKeySecretRef:
            namespace: external-secrets
            name: patch-me-gcp-credentials-secret-name
            key: secret-access-credentials
      projectID: patch-me-project-id