apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: infra-onepassword-store
  namespace: external-secrets
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  provider:
    onepasswordSDK:
      auth:
        serviceAccountSecretRef:
          key: token
          name: patch-me-access-token-secret-name
          namespace: patch-me-access-token-namespace
      integrationInfo:
        name: integration-info
        version: v1
      vault: patch-me-vault-name
