apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

resources:
  - namespace.yaml
  - subscription.yaml
  - operatorconfig.yaml
  - secretstore.yaml

commonLabels:
  component: external-secrets-infra
