apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-autocert-ca-bundle
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  rules:
    - name: add-ca-bundle-to-autocert
      context:
        - name: labCaBundle
          configMap:
            name: lab-ca-bundle
            namespace: openshift-config
      match:
        all:
          - resources:
              kinds:
                - StepIssuer
              namespaces:
                - pki
              names:
                - step-issuer
      mutate:
        patchStrategicMerge:
          spec:
            +(caBundle): '{{ labCaBundle.data."ca-bundle.crt" }}'
