---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-minio-operator-sa-nonroot-v2
  namespace: minio-operator
subjects:
- kind: ServiceAccount
  name: minio-operator
  namespace: minio-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-nonroot-v2-scc
