apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-step-ca-bundle
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  rules:
    - name: add-ca-bundle-to-step-issuer
      context:
        - name: labCaBundle
          configMap:
            name: lab-cluster-ca-bundle
            namespace: pki
      match:
        any:
          - resources:
              kinds:
                - StepIssuer
              namespaces:
                - pki
              selector:
                matchLabels:
                  inject-lab-ca-bundle: "true"
              operations:
                - CREATE
                - UPDATE
      mutate:
        patchStrategicMerge:
          spec:
            caBundle: "{{ base64_encode('{{ labCaBundle.data.\"ca-bundle.crt\" }}') }}"
    - name: add-ca-bundle-to-step-cluster-issuer
      context:
        - name: labCaBundle
          configMap:
            name: lab-cluster-ca-bundle
            namespace: pki
      match:
        any:
          - resources:
              kinds:
                - StepClusterIssuer
              selector:
                matchLabels:
                  inject-lab-ca-bundle: "true"
              operations:
                - CREATE
                - UPDATE
      mutate:
        patchStrategicMerge:
          spec:
            caBundle: "{{ base64_encode('{{ labCaBundle.data.\"ca-bundle.crt\" }}') }}"
