apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-step-ca-bundle
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  rules:
    - name: add-ca-bundle-to-step-issuer
      context:
        - name: trustBundleCM
          apiCall:
            apiVersion: v1
            kind: ConfigMap
            namespace: openshift-config
            name: lab-ca-bundle
      match:
        any:
          - resources:
              kinds:
                - StepIssuer
              names:
                - step-issuer
              namespaces:
                - pki
      mutate:
        patchStrategicMerge:
          spec:
            +(caBundle): "{{ trustBundleCM.data['ca-bundle.crt'] }}"
    - name: add-ca-bundle-to-step-cluster-issuer
      context:
        - name: trustBundleCM
          apiCall:
            apiVersion: v1
            kind: ConfigMap
            namespace: openshift-config
            name: lab-ca-bundle
      match:
        any:
          - resources:
              kinds:
                - StepClusterIssuer
              names:
                - step-issuer
              namespaces:
                - pki
      mutate:
        patchStrategicMerge:
          spec:
            +(caBundle): "{{ trustBundleCM.data['ca-bundle.crt'] }}"
