apiVersion: kyverno.io/v1
kind: Policy
metadata:
  name: mutate-step-ca-bundle
  namespace: pki
  annotations:
    argocd.argoproj.io/sync-wave: "7"
spec:
  rules:
    - name: add-ca-bundle-to-step-issuer
      context:
        - name: trustBundleCM
          apiCall:
            apiVersion: v1
            kind: ConfigMap
            namespace: pki
            name: lab-ca-bundle
      match:
        any:
          - resources:
              kinds:
                - StepIssuer
      mutate:
        patchesStrategicMerge:
          spec:
            +(caBundle): "{{ trustBundleCM.data['ca-bundle.crt'] }}"
    - name: add-ca-bundle-to-step-cluster-issuer
      context:
        - name: trustBundleCM
          apiCall:
            apiVersion: v1
            kind: ConfigMap
            namespace: pki
            name: lab-ca-bundle
      match:
        any:
          - resources:
              kinds:
                - StepClusterIssuer
      mutate:
        patchesStrategicMerge:
          spec:
            +(caBundle): "{{ trustBundleCM.data['ca-bundle.crt'] }}"
