apiVersion: certmanager.step.sm/v1beta1
kind: StepIssuer
metadata:
  name: step-issuer
  namespace: pki
spec:
  # Force using system root certificates by omitting /spec/caBundle
  #   https://github.com/smallstep/helm-charts/blob/master/step-issuer/crds/certmanager.step.sm_stepclusterissuers.yaml#L37
  # caBundle: a3l2ZXJuby1yZXBsYWNlcy1tZQo=
  url: https://pki.lab.cross.solutions
  provisioner:
    name: ocp-cert-manager-lab
    kid: "At3bv3OxIXZki-90c1es7kKsk-fHkY4uJoBxSLKSeMY"
    passwordRef:
      name: step-issuer-provisioner-password
      key: password
