---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-nonroot-v2-scc
  namespace: pki
rules:
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  resourceNames:
    - nonroot-v2
  verbs:
    - use
