apiVersion: trust.cert-manager.io/v1alpha1
kind: Bundle
metadata:
  name: lab-cluster-ca-bundle
spec:
  sources:
  - useDefaultCAs: false

  - secret:
      name: lab-ca-bundle
      key: ca-bundle.crt
  target:
    configMap:
      key: ca-bundle.crt
      metadata:
        labels:
          app.kubernetes.io/component: "trust-bundle"
    namespaceSelector:
      matchExpressions:
        - key: kubernetes.io/metadata.name
          operator: In
          values:
            - openshift-config
