---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator-openshift-virtualization
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  destination:
    namespace: democratic-csi
    server: https://kubernetes.default.svc
  project: local-cluster
  sources:
    - chart: democratic-csi
      helm:
        valueFiles:
          - $values/openshift-gitops/clusters/core.lab.cross.solutions/platform-apps/operator-openshift-virtualization
      repoURL: 'https://democratic-csi.github.io/charts/'
      targetRevision: 0.14.7
    - ref: values
      repoURL: 'https://github.com/wtcross/homelab'
      targetRevision: main
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
