---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  destination:
    namespace: vault
    server: https://kubernetes.default.svc
  project: local-cluster
  sources:
    - chart: vault
      helm:
        valueFiles:
          - $values/openshift-gitops/clusters/core.lab.cross.solutions/helm-values/vault.yaml
      repoURL: 'https://helm.releases.hashicorp.com'
      targetRevision: 0.29.1
    - ref: values
      repoURL: 'https://github.com/wtcross/homelab'
      targetRevision: main
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: MutatingWebhookConfiguration
      jqPathExpressions:
        - .webhooks[]?.clientConfig.caBundle
  syncPolicy:
    automated:
      allowEmpty: false
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
