---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-virt-storage-profiles
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "13"
  labels:
    has-git-repo-objects: "true"
spec:
  destination:
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/wtcross/homelab
      targetRevision: main
      path: openshift-gitops/clusters/core.lab.cross.solutions/platform-apps/openshift-virt-storage-profiles
  project: local-cluster
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
