---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - git-config-map.yaml
  - 01-cluster-version.yaml
  - 02-machineconfigs.yaml
  - 03-aggregate-nmstate.yaml
  - 03-aggregate-node-feature-discovery.yaml
  - 03-democratic-csi-nfs.yaml
#  - 03-democratic-csi-iscsi.yaml
  - 04-consul.yaml
  - 05-vault.yaml
  - 06-operator-eso.yaml
  - 07-instance-eso.yaml
  - 20-operator-openshift-dev-spaces.yaml
  - 21-instance-openshift-dev-spaces.yaml
  - 30-operator-ansible-automation-platform.yaml

replacements:
  - source:
      kind: ConfigMap
      name: git-config
      fieldPath: data.repoBase
    targets:
      - select:
          kind: Application
          group: argoproj.io
          labelSelector: has-git-repo-objects=true
        fieldPaths:
        - spec.sources.*.repoURL
