---
apiVersion: v1
kind: Node
metadata:
  name: core0.lab.cross.solutions
---
apiVersion: v1
kind: Node
metadata:
  name: core1.lab.cross.solutions
---
apiVersion: v1
kind: Node
metadata:
  name: core2.lab.cross.solutions
