---
apiVersion: console.openshift.io/v1
kind: ConsoleLink
metadata:
  name: gcp-console
spec:
  applicationMenu:
    section: Cloud
    imageURL: data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmciIHZpZXdCb3g9IjAgMCA5Ny43NSA3OC42MiI+PHBhdGggZD0iTTYyLjIxIDIxLjczbDMuMTMuMDYgOC41My04LjUxLjQyLTMuNmEzOC4yIDM4LjIgMCAwIDAtNjIuMyAxOC41N2MuODgtLjY0IDIuODgtLjE2IDIuODgtLjE2bDE3LTIuOHMuODgtMS40NCAxLjMxLTEuMzVhMjEuMTkgMjEuMTkgMCAwIDEgMjktMi4yMXoiIGZpbGw9IiNlYTQzMzUiLz48cGF0aCBkPSJNODUuNzkgMjguMjdhMzguMzIgMzguMzIgMCAwIDAtMTEuNTQtMTguNmwtMTIgMTJhMjEuMiAyMS4yIDAgMCAxIDcuOTIgMTYuNTN2Mi4xOWExMC42MyAxMC42MyAwIDEgMSAwIDIxLjI1aC0yMS4zbC0yLjEyIDIuMTR2MTIuNzNsMi4xMiAyLjEyaDIxLjI1YTI3LjYxIDI3LjYxIDAgMCAwIDE1LjY3LTUwLjM2eiIgZmlsbD0iIzQyODVmNCIvPjxwYXRoIGQ9Ik0yNy42MiA3OC42M2gyMS4yNXYtMTdIMjcuNjJhMTAuNTQgMTAuNTQgMCAwIDEtNC4zOC0xbC0zLjA2Ljk0LTguNTEgOC41NS0uNzQgMi44OGEyNy40NyAyNy40NyAwIDAgMCAxNi42OSA1LjYzeiIgZmlsbD0iIzM0YTg1MyIvPjxwYXRoIGQ9Ik0yNy42MiAyMy4zOUEyNy42MSAyNy42MSAwIDAgMCAxMC45NCA3M2wxMi4zMi0xMi4zMmExMC42MiAxMC42MiAwIDEgMSAxNC0xNGwxMi4zNi0xMi4zNmEyNy42IDI3LjYgMCAwIDAtMjItMTAuOTN6IiBmaWxsPSIjZmJiYzA0Ii8+PC9zdmc+
  href: https://console.cloud.google.com
  location: ApplicationMenu
  text: Google Cloud Console
