apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: keycloak-db-creds
  namespace: keycloak
spec:
  data:
    - remoteRef:
        key: core-keycloak-db-user
      secretKey: user
    - remoteRef:
        key: core-keycloak-db-password
      secretKey: password
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: gcpsm-cluster-secret-store
  target:
    name: keycloak-db-creds
    creationPolicy: Owner
