apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-secret-key
  namespace: harbor
spec:
  data:
    - remoteRef:
        key: core-harbor-secret-key
      secretKey: secretKey
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infra-gcpsm-store
  target:
    name: harbor-secret-key
    creationPolicy: Owner
