apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-admin-password
  namespace: harbor
spec:
  data:
    - remoteRef:
        key: core-harbor-admin-password
      secretKey: HARBOR_ADMIN_PASSWORD
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infra-gcpsm-store
  target:
    name: harbor-admin-password
    creationPolicy: Owner
