apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: harbor-registry-secret
  namespace: harbor
spec:
  data:
    - remoteRef:
        key: core-harbor-registry-secret
      secretKey: secret
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infra-gcpsm-store
  target:
    name: harbor-registry-secret
    creationPolicy: Owner
