apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lab-ca-root
  namespace: pki
spec:
  data:
    - remoteRef:
        key: lab-ca-root
      secretKey: caRoot
  refreshInterval: 1h0m0s
  secretStoreRef:
    kind: ClusterSecretStore
    name: infra-gcpsm-store
  target:
    name: lab-ca-root
    creationPolicy: Owner
    template:
      engineVersion: v2
      metadata:
        annotations:
          reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
          reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "pki,openshift-config"
      data:
        ca.crt: {{ .caRoot | trim | b64enc }}
