apiVersion: external-secrets.io/v1alpha1
kind: PushSecret
metadata:
  name: layered-image-global-pull-secret
spec:
  refreshInterval: 1h
  secretStoreRefs:
    - name: k8s-store-remote-ns
      kind: SecretStore
  selector:
    secret:
      name: pokedex-credentials
  data:
    - match:
        secretKey: best-pokemon
        remoteRef:
          remoteKey: remote-best-pokemon
          property: best-pokemon