---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thunderbolt-base
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    has-git-repo-objects: "true"
spec:
  destination:
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://github.com/wtcross/homelab
      targetRevision: main
      path: openshift-gitops/clusters/core.lab.cross.solutions/platform-apps/thunderbolt-base/
  project: local-cluster
  syncPolicy:
    automated:
      prune: false
      allowEmpty: true
      selfHeal: true
