---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: aap-openshift-virt-read
  namespace: tyler-vms
rules:
  - apiGroups:
      - kubevirt.io
    resources:
      - virtualmachines
      - virtualmachineinstances
    verbs:
      - get
      - watch
      - list
  - apiGroups:
      - ""
    resources:
      - services
      - endpoints
    verbs:
      - get
      - watch
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: aap-openshift-virt-read
  namespace: tyler-vms
subjects:
- kind: ServiceAccount
  name: aap-openshift-virt-reader
  namespace: ansible-automation-platform
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: aap-openshift-virt-read
