apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: clair-pg
  namespace: clair
spec:
  description: Clair PostgreSQL cluster
  instances: 3
  logLevel: info
  primaryUpdateStrategy: unsupervised
  storage:
    size: 15Gi
    storageClass: lvms-vg1
  walStorage:
    size: 2Gi
    storageClass: lvms-vg1
  certificates:
    serverCASecret: clair-pg-certificate
    serverTLSSecret: clair-pg-certificate
  postgresql:
    pg_hba:
      - hostssl app app all scram-sha-256
