---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-restricted-v2-scc
rules:
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  resourceNames:
    - restricted-v2
  verbs:
    - use
