---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-restricted-v2-scc
  namespace: kyverno
rules:
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  resourceNames:
    - restricted-v2
  verbs:
    - use
