apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: cluster-api
  namespace: openshift-config
spec:
  secretName: cluster-api-certificate
  duration: 1440h
  renewBefore: 72h
  issuerRef:
    group: certmanager.step.sm
    kind: StepClusterIssuer
    name: step-issuer
  commonName: 'api.core.lab.cross.solutions'
  dnsNames:
    - 'api.core.lab.cross.solutions'
