---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: core0
spec:
  machineConfigSelector:
    matchLabels:
      machineconfiguration.openshift.io/role: core0
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/core0: ''
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: core1
spec:
  machineConfigSelector:
    matchLabels:
      machineconfiguration.openshift.io/role: core1
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/core1: ''
---
apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfigPool
metadata:
  name: core2
spec:
  machineConfigSelector:
    matchLabels:
      machineconfiguration.openshift.io/role: core2
  nodeSelector:
    matchLabels:
      node-role.kubernetes.io/core2: ''
