---
apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
spec:
  channel: stable-4.19
  clusterID: bbc4c48f-8600-43d7-9ab9-662b93dfd0be
  desiredUpdate:
    version: 4.19.5
