---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-apps
  namespace: openshift-gitops
spec:
  destination:
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/wtcross/homelab
    targetRevision: main
    path: openshift-gitops/clusters/core.lab.cross.solutions/platform-apps
  project: local-cluster
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
