---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/wtcross/gitops-catalog/openshift-gitops-operator/instance/overlays/default?ref=main
  - rbac.yaml
  - argocd-AppProject.yaml
  - argocd-AppOfApps.yaml
  - argocd-repo.yaml
