apiVersion: config.openshift.io/v1
kind: ClusterVersion
metadata:
  name: version
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  channel: stable-4.20
  clusterID: bbc4c48f-8600-43d7-9ab9-662b93dfd0be
  desiredUpdate:
    version: 4.20.3
