---
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: truenas-nfs-nonroot
spec:
  claimPropertySets:
    - accessModes:
        - ReadWriteMany
        - ReadWriteOnce
      volumeMode:
        Filesystem
---
apiVersion: cdi.kubevirt.io/v1beta1
kind: StorageProfile
metadata:
  name: truenas-iscsi-nonroot
spec:
  claimPropertySets:
    - accessModes:
        - ReadWriteOnce
      volumeMode:
        Block
