apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-kyverno-sa-use-nonroot-v2-scc
  namespace: kyverno
subjects:
- kind: ServiceAccount
  name: kyverno-migrate-resources
  namespace: kyverno
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-nonroot-v2-scc
