---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: use-anyuid-seccomp-scc
  namespace: harbor
rules:
- apiGroups:
    - security.openshift.io
  resources:
    - securitycontextconstraints
  resourceNames:
    - anyuid-seccomp
  verbs:
    - use