---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: add-workspace-networkpolicy
spec:
  rules:
    - name: add-networkpolicy-to-workspace
      match:
        resources:
          kinds:
            - Namespace
          name: "che*-*-devspaces-*"
      generate:
        kind: NetworkPolicy
        apiVersion: networking.k8s.io/v1
        name: allow-ingress-from-devspaces-gateway
        namespace: "{{ request.object.metadata.name }}"
        synchronize: true
        data:
          spec:
            podSelector: {}
            ingress:
              - from:
                  - namespaceSelector:
                      matchLabels:
                        kubernetes.io/metadata.name: openshift-devspaces
            policyTypes:
              - Ingress
