apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: patch-cluster-proxy
rules:
  - apiGroups:
      - config.openshift.io
    resources:
      - proxies
    verbs:
      - get
      - list
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: patch-cluster-proxy
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: patch-cluster-proxy
subjects:
  - kind: ServiceAccount
    name: patch-cluster-proxy
    namespace: openshift-config
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: patch-cluster-proxy
  namespace: openshift-config
---
apiVersion: batch/v1
kind: Job
metadata:
  name: patch-cluster-proxy
  namespace: openshift-config
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
        - image: quay.io/openshift/origin-cli:latest
          command:
            - /bin/bash
            - -c
            - |
              #!/usr/bin/env bash
              oc patch proxy/cluster --type=merge --patch='{"spec":{"trustedCA":{"name":"lab-ca-bundle"}}}'
          name: patch-cluster-proxy
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      terminationGracePeriodSeconds: 30
      serviceAccount: patch-cluster-proxy
      serviceAccountName: patch-cluster-proxy
