apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: seaweed-quay-master-pdb
  namespace: quay
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/instance: seaweed-quay
      app.kubernetes.io/component: master
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: seaweed-quay-volume-pdb
  namespace: quay
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/instance: seaweed-quay
      app.kubernetes.io/component: volume
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: seaweed-quay-filer-pdb
  namespace: quay
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: seaweedfs
      app.kubernetes.io/instance: seaweed-quay
      app.kubernetes.io/component: filer
