apiVersion: seaweed.seaweedfs.com/v1
kind: Seaweed
metadata:
  name: seaweed-quay
  namespace: quay
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  image: chrislusf/seaweedfs:latest
  volumeServerDiskCount: 1

  affinity:
    podAntiAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
        - weight: 100
          podAffinityTerm:
            topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app.kubernetes.io/name: seaweedfs
                app.kubernetes.io/instance: seaweed-quay

  master:
    replicas: 3
    volumeSizeLimitMB:

  volume:
    replicas: 3
    storageClassName: lvms-vg1
    requests:
      storage: 100Gi

  filer:
    replicas: 2
    s3:
      enabled: true
      configSecret:
        name: seaweed-s3-config
        key: s3-config.json
    requests:
      storage: 10Gi
    config: |
      [leveldb2]
      enabled = true
      dir = "/data/filerldb2"
