---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: allow-default-sa-anyuid-seccomp
  namespace: harbor
subjects:
- kind: ServiceAccount
  name: default
  namespace: harbor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: use-anyuid-seccomp-scc
