kind: Secret
apiVersion: v1
metadata:
  name: seaweedfs-ca-cert
type: Opaque
data:
  tls.crt: |
    -----BEGIN CERTIFICATE-----
    MIICyzCCAlGgAwIBAgIUM701Oc8uB35avhhliU9rgzrXwogwCgYIKoZIzj0EAwQw
    gZIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEYMBYGA1UE
    CgwPQ3Jvc3MgU29sdXRpb25zMS4wLAYDVQQLDCVDcm9zcyBTb2x1dGlvbnMgQ2Vy
    dGlmaWNhdGUgQXV0aG9yaXR5MSAwHgYDVQQDDBdDcm9zcyBTb2x1dGlvbnMgUm9v
    dCBDQTAeFw0yNTEyMDgxMTI0MjBaFw0zNTEyMDYxMTI0MjBaMIGSMQswCQYDVQQG
    EwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExGDAWBgNVBAoMD0Nyb3NzIFNv
    bHV0aW9uczEuMCwGA1UECwwlQ3Jvc3MgU29sdXRpb25zIENlcnRpZmljYXRlIEF1
    dGhvcml0eTEgMB4GA1UEAwwXQ3Jvc3MgU29sdXRpb25zIFJvb3QgQ0EwdjAQBgcq
    hkjOPQIBBgUrgQQAIgNiAAQvXittluoOkXni2wtRn6SuZokbEOq37iKYfi6IDqIg
    ubXtCzEz+HP3iB7cwJC8kCP5R4k1EEGjrWqE9aGUb0ne2ZDxxrmQ1BIHly4R7DRI
    B0YjSsGP5denuRSzSnGPxhijZjBkMB0GA1UdDgQWBBRHsedFvBF1un0LhTJqfJaU
    41axgDAfBgNVHSMEGDAWgBRHsedFvBF1un0LhTJqfJaU41axgDASBgNVHRMBAf8E
    CDAGAQH/AgEBMA4GA1UdDwEB/wQEAwIBhjAKBggqhkjOPQQDBANoADBlAjEA7YrA
    ZRETyf06DLv7lmx7b1dSxUGnTaLRXDLipIVH3nAvIlBPKSHtvOBK1LNxhExdAjBj
    yLwaBS7uq0lshwJAGzMlmsQbKe8IveTJwlIHdmykz8x/2M6SU0MDygXeqXG8fsI=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIC1DCCAlmgAwIBAgIUZ8HS7WgjRcHKbk1ZcEjdH0Pmr6YwCgYIKoZIzj0EAwQw
    gZIxCzAJBgNVBAYTAlVTMRcwFQYDVQQIDA5Ob3J0aCBDYXJvbGluYTEYMBYGA1UE
    CgwPQ3Jvc3MgU29sdXRpb25zMS4wLAYDVQQLDCVDcm9zcyBTb2x1dGlvbnMgQ2Vy
    dGlmaWNhdGUgQXV0aG9yaXR5MSAwHgYDVQQDDBdDcm9zcyBTb2x1dGlvbnMgUm9v
    dCBDQTAeFw0yNTEyMDgyMTIxMDJaFw0zMDEyMDcyMTIxMDJaMIGaMQswCQYDVQQG
    EwJVUzEXMBUGA1UECAwOTm9ydGggQ2Fyb2xpbmExGDAWBgNVBAoMD0Nyb3NzIFNv
    bHV0aW9uczEuMCwGA1UECwwlQ3Jvc3MgU29sdXRpb25zIENlcnRpZmljYXRlIEF1
    dGhvcml0eTEoMCYGA1UEAwwfQ3Jvc3MgU29sdXRpb25zIEludGVybWVkaWF0ZSBD
    QTB2MBAGByqGSM49AgEGBSuBBAAiA2IABCWzuQ/1ivs6Q3+tUfrDLH3pW2QFJoqO
    yRjydPDTpqzIsWM6qBgnptzP0HbVYSW/IMIus/O6MEwQ34GwQMRnoF7xpze4n9L1
    Jt/VK8uFLMmG/xBdYS1eUHulJY7suBibsaNmMGQwHQYDVR0OBBYEFEFhYucVGsy7
    FGpk44pug+GrlIF0MB8GA1UdIwQYMBaAFEex50W8EXW6fQuFMmp8lpTjVrGAMBIG
    A1UdEwEB/wQIMAYBAf8CAQEwDgYDVR0PAQH/BAQDAgGGMAoGCCqGSM49BAMEA2kA
    MGYCMQCIKYA//2V7/0drFs7TZqjAyBuEg1/qpi2s76JNqaw3ga3Y2Xj/U/Q8z8VJ
    IF9JfCgCMQDD1zSdki4u/AfPn4xLbMoY5Zo2/3SgoSxgK61mttH/vwgcdYnZiCTH
    ezyOaUusEwI=
    -----END CERTIFICATE-----
