apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  description: "Common platform configuration"
  sourceRepos:
    - 'https://github.com/wtcross/homelab.git'
    - 'https://kyverno.github.io/kyverno/'
    - 'https://smallstep.github.io/helm-charts'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
