apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudnative-pg
  annotations:
    argocd.argoproj.io/sync-wave: "50"
    argocd.argoproj.io/compare-options: ServerSideDiff=true,IncludeMutationWebhook=true
spec:
  project: platform
  source:
    chart: cloudnative-pg
    repoURL: 'https://cloudnative-pg.github.io/charts'
    targetRevision: patch-me-source-revision
    helm:
      releaseName: cloudnative-pg
      valuesObject: patch-me-values-object
  destination:
    server: https://kubernetes.default.svc
    namespace: cnpg-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true
